---
# Handlers for omero-common

# The conditional means you can safely notify this on non-systemd servers
- name: reload systemd
  become: yes
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: restart omero-server
  become: yes
  service:
    name: omero-server
    state: restarted

- name: restart omero-web
  become: yes
  service:
    name: omero-web
    state: restarted

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
