---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  # These two containers test that the "reload systemd" handler can be
  # notified regardless of systemd status
  - name: omero-common
    image: centos:7
  - name: omero-common-systemd
    image: centos/systemd:latest
  - name: ubuntu-1804
    image: ubuntu:18.04
    # TODO: Find an Ubuntu Systemd container suitable for testing
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
