---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: rockylinux
    image: rockylinux:9
  - name: ubuntu-22.04
    image: ubuntu:22.04
  # These two containers test that the "reload systemd" handler can be
  # notified regardless of systemd status
  # TODO: Find an Ubuntu and RockyLinux Systemd  suitable for testing
  # - name: omero-common-systemd # not sure what to do with that
  #   image: centos/systemd:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
